import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Importing fonts using next/font API
const geistSans = Geist({
  subsets: ["latin"],  // You can keep the subsets here
});

const geistMono = Geist_Mono({
  subsets: ["latin"],  // Same here for Geist_Mono
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
